[tool.poetry]
name = "quotaclimat"
version = "0.1.0"
description = ""
authors = ["Rambier Estelle <estelle.rambier@hotmail.fr>"]
readme = "README.md"

[[tool.poetry.source]]
name = "pypi-public"
url = "https://pypi.org/simple/"

[tool.poetry.dependencies]
python = "^3.10"
plotly = "^5.10.0"
pandas = "^1.5.0"
nltk = "^3.7"
matplotlib = "^3.6.1"
ipykernel = "^6.16.0"
nbformat = "^5.7.0"
openpyxl = "^3.0.10"
jupyter = "^1.0.0"
notebook = "^6.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pre-commit = "^2.18.1"
black = "^22.3.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
invoke = "^1.7.3"