name: test-cyprus-data-models

on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'
  POETRY_VERSION: '1.2.1'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: psf/black@stable
      - name: flake8 Lint
        uses: py-actions/flake8@v2
      - uses: isort/isort-action@master

  test-quotaclimat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --no-root --sync

      - name: Run tests with pytest
        run: poetry run pytest
